[package]
name = "falling-snow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
termgrid = { git = "https://github.com/twallie/termgrid", version = "0.1.0" }
